### ISSUE TITLE
Refresh post

### ISSUE THREAD

**Issue by axelverglas** [gregrickaby/nextjs-wordpress#142]
Congratulation for this amazing project !!
I have a cache problem I think because my posts don't update on my site as soon as I post one except when I force dynamic reloading...

**Comment by gregrickaby** [comment]
@axelverglas I've adjusted the revalidate route to bust all cache in this commit https://github.com/gregrickaby/nextjs-wordpress/commit/bddd6bbefa555c9401ab0967c14162ad03519b88

On other projects I run, I've found the best way to revalidate is to revalidate all paths.
