### ISSUE TITLE
Primary & Footer Menu Support

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/nextjs-wordpress#25]
I'd like to introduce a new menu in the footer. An easy way for a user to add some links without adding code.

- [ ] Need to register `Footer` menu 
- [ ] Query `Footer` menu
- [ ] Display and style `Footer` menu in `<Footer />`

**Comment by leonlafa** [comment]
I'm happy to take this one if it's up for grabs?

**Comment by leonlafa** [comment]
**FYI:** I've made a start on this issue.

I've completed:

- [x] Register Footer menu
- [x] Query Footer menu
- [ ] Display and style Footer menu

I have to make a road trip but I will be back in a couple of hours to finish it off and create a PR.
