### ISSUE TITLE
Improve Quick Start / Create Script

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/nextjs-wordpress#30]
Right now, there is nothing "quick" about the [Quick Start](https://github.com/gregrickaby/nextjs-wordpress/blob/main/README.md#quick-start). 🤣

I would prefer there be a setup script that a user can run to stand up a development environment.

- [ ] Use the steps in "Quick Start" to create a simple script that will run on 'nix and Windows
- [ ] Put the script in the root of the project
- [ ] Add instructions to the "Quick Start" section of the README

**Comment by leonlafa** [comment]
I'll jump on this one 😄

**Comment by gregrickaby** [comment]
💪🏻
