### ISSUE TITLE
ESLint isn't ignoring folders listed in .eslintignore

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/nextjs-wordpress#33]
I don't know why, but when I run `npm run lint` at the root of the project, ESLint is not ignoring the folders listed in `.eslintignore`.

- [ ] Read Turborepo [docs on ESLint](https://turborepo.org/docs/handbook/linting/eslint)
- [ ] Find out why it is not ignoring folders
- [ ] Fix it

**Comment by ahmedsilat44** [comment]
Hey @gregrickaby I’d like to work on this issue could you assign it to me. Thanks 😄

**Comment by gregrickaby** [comment]
Sure thing! Please see the [Contributing guidelines](https://github.com/gregrickaby/nextjs-wordpress/blob/main/CONTRIBUTING.md). Thanks!

**Comment by ahmedsilat44** [comment]
@gregrickaby Hey. Sorry I couldn't find what the problem was. I'll unassign myself from this issue. Good Luck on getting it solver 👍

**Comment by gregrickaby** [comment]
Fix with https://github.com/gregrickaby/nextjs-wordpress/commit/ef50cc1f2a9923629193afcc9813aec4295cc81d
