### ISSUE TITLE
Create <WordPressProvider /> Component to House Context

### ISSUE THREAD

**Issue by gregrickaby** [gregrickaby/nextjs-wordpress#37]
I feel like global-y things like Menus, Settings, SEO, etc... should be managed in a new `<WordpressProvider />` component, rather than passed down by every query.

- [x] Create `<WordPressProvider />` component (it should follow [this pattern](https://github.com/gregrickaby/local-weather/blob/main/components/WeatherProvider.tsx))
- [x] The Provider should have a `useWordPress()` hook
- [x] Add new provider to `_app.tsx`
- [x] Create a query for global items like menus, settings, and SEO
- [x] Place query results into state
- [x] Use the `useWordPress()` hook to grab the state and pass into other components like, `<Layout />`

**Comment by gregrickaby** [comment]
Because I removed Tailwind, I might as well spin up a provider as part of #26. Less to juggle!

**Comment by leonlafa** [comment]
I feel like global-y things like Menus, Settings, SEO, etc... should be managed in a new `<WordpressProvider />` component, rather than passed down by every query.

Yeah, I agree,  this would be a better solution.

**Comment by leonlafa** [comment]
> I feel like global-y things like Menus, Settings, SEO, etc... should be managed in a new `<WordpressProvider />` component, rather than passed down by every query.



Yeah, I agree,  this would be a better solution.
