### ISSUE TITLE
docs/feature: Block development / shared UI library

### ISSUE THREAD

**Issue by data-envoy** [gregrickaby/nextjs-wordpress#84]
Hi, your project looks really interesting.

Do you have a suggested way to build a Gutenberg block locally, with a nice DX and code that can be shared across nextjs and WP?

**Comment by gregrickaby** [comment]
@data-envoy On my personal site, I have a [custom ACF Block](https://github.com/gregrickaby/gregrickaby.com-wordpress/blob/main/plugins/grd-photo-gallery/src/blocks/gallery/block.json) for displaying photo galleries. On my front-end, I use [this Component](https://github.com/gregrickaby/gregrickaby/blob/main/components/Blocks.tsx) to display it by scanning the incoming content for a CSS class and then mounting on `useEffect()`. The implementation works really well!

Good luck!
