### ISSUE TITLE
feature request: Registration and Login

### ISSUE THREAD

**Issue by Pfurr** [gregrickaby/nextjs-wordpress#87]
Congratulations on the project. I wanted to try this project, however I have a problem: I still need a front end that handles user registration and login. How is this possible?

**Comment by denvergj** [comment]
You can just create endpoints in the API and call them via the frontend NextJS.

**Comment by gregrickaby** [comment]
I agree with @denvergj. I would use https://next-auth.js.org/ and create a custom provider.
